### ISSUE TITLE
Admin claim not added removed based on 'role' field in queries

### ISSUE THREAD

**Issue by johnchen383** [UoaWDCC/nzpmc-exam-portal#263]
~~checkRole not utilized in utils/Auth.ts~~
- [X] Add claims based on firebase role
- [X] Remove claims based on firebase role
- [x] ~~Integrate Enums (?)~~
- [ ] Comprehensive edge case/error handling
- [ ] More performant means of adding admin claims

**Comment by bcho892** [comment]
I have gotten to a point where this is claim is implemented based on the condition that the uid does have a document in the users collection (I haven't tested it yet for if a document doesn't exist)
