### ISSUE TITLE
Auth: Complete

### ISSUE THREAD

**Issue by Oculux314** [UoaWDCC/nzpmc-exam-portal#355]
### Description:

As title.
Unblocks #302.

### Acceptance Criteria:
- [ ] Figma design fully implemented
- [ ] Bugs fixed
- [ ] Tested
- [ ] #302 notified when done

### Definition of Done:
- [ ] AC met
- [ ] PR linked
- [ ] Branch merged

### Notes
Continues #316.
A branch for this ticket exists already: 316_implement-auth-page.
Known bug: back button.

**Comment by johnchen383** [comment]
Text fields
Sign In Redesign
Back button + bug going back
Error message alert

**Comment by else861** [comment]
bug: after pressing forgot password and resetting it, sign in button doesn't work
could redesign "forgot password" page
