### ISSUE TITLE
Admin: Enrollment Logic

### ISSUE THREAD

**Issue by Oculux314** [UoaWDCC/nzpmc-exam-portal#356]
### Description:

Implement enrolment functionality (logic/scripts only) for admin page.
Batch CSV enrolment required only.
Builds on #274.

### Acceptance Criteria:
- [x] Check user management functionality complete & correct
- [ ] Batch enrollment/disenrolment/download functionality added (CSV)
- [ ] Auto-adds users when enrolling if they don't exist already
- [ ] Individual-by-individual error handling for invalid input
- [ ] Tested on real data* (IMPORTANT: DON'T COMMIT)

### Definition of Done:
- [ ] AC met
- [ ] PR linked
- [ ] Branch merged

### Notes
\* Nate has samples.

**Comment by johnchen383** [comment]
Assigning
(Assuming exam created, and we’ve selected exam)
CSV of users (fields defined)
If user DNE, add to Firebase + enrol to exam
If user exists, enrol to exam
Upload CSV
Send to API
