### ISSUE TITLE
Exam Management: Overwrite On Enrol

### ISSUE THREAD

**Issue by Oculux314** [UoaWDCC/nzpmc-exam-portal#412]
### Description:

Bugfix: overwrite not add on enrolment.

### Acceptance Criteria:
- [x] Enrolling students via CSV OVERWRITES existing students rather than adding to them.*
- [x] "Quiz Management" tab renamed to "Exam Management".**

### Definition of Done:
- [x] AC met
- [x] PR linked
- [x] Branch merged

### Notes
\* Don't change how user management works - adding users should still add not overwrite users.
\** Unrelated, but since you've already got the file open... ¯\\\_(ツ)\_/¯

**Comment by ardo715** [comment]
i in fact did not already have the file open
